### ISSUE TITLE
intu : unable to click the next button

### ISSUE THREAD

**Issue by entheos37** [watson-intu/self-sdk#15]
I followed the workshop 1: Saying Hello guideline.

After installing intu, I could not click the next button. 

9. Click Next. A "Connecting to parent..." message is displayed while your Intu Manager tries to establish a connection. When the connection is made, the status icon of the device you installed Intu on turns green. 

-> I want to do this 9th step, but I was unable to click the next button. 

I am a mac user. 

I would really appreciate that if someone can tell me the solution. 

Thank you!!

**Comment by swizardlv** [comment]
i met same issue .  work around is creating a new org and group and change the credentials of the default ones.

**Comment by ereneld** [comment]
@entheos37 this is data issues that we are seeing. As a workaround like @swizardlv  said, you can create new org / group and try to login with it and delete the old org you have. 
Tooling will show the proper error in the upcoming release. Thanks.
