### ISSUE TITLE
How do I get Intu to use my Conversation workspace?

### ISSUE THREAD

**Issue by LabPM** [watson-intu/self-sdk#20]
I installed Intu on my Mac. In the gateway, I have already configured the conversation service. But I couldn't get Intu to connect to one of my workspaces in the conversation service. The workspace contains all the dialogs/intents/entities.

**Comment by LabPM** [comment]
In Intu Gateway, the Conversation service has two key value pairs called "self_dialog" and "self_domain." Replace self-dialog with your workspace id. Then, import our starter kit into another workspace. The starter kit is available in Intu Gateway under Downloads. And put that workspace id into the self_domain field.

**Comment by gitwouter** [comment]
Does this mean that the parameter "self_dialog" points to whatever first conversation workspace one wants to use and "self_domain" to an optional second conversation workspace? What if there is a third conversation workspace?

**Comment by rolyle** [comment]
For that, you would need to add a third "ConversationProxy" to the TextClassifier object in the body.json. In fact, you can add as many of these as you need, keeping in mind the TextClassifier is going to act upon the one with the highest confidence.

**Comment by gitwouter** [comment]
ah, ok, now I see that it is in body.json, with m_WorkspaceKey, that one defines the name of the parameter to put the workspace ID in. thanks!
