### ISSUE TITLE
Having trouble "Connecting to parent..." in intu monitor

### ISSUE THREAD

**Issue by luthraprerna** [watson-intu/self-sdk#4]
I am having trouble "Connecting to parent.." in intu monitor. It was taking way too long to connect to it. In the terminal, there were endless Websocket 'failed to connect' messages and then in the intu monitor UI, the box kept showing a spinning circle and wasn't turning green. 
<img width="1440" alt="screen shot 2016-11-16 at 12 36 06 pm" src="https://cloud.githubusercontent.com/assets/22749897/20358772/0fadd90c-abfb-11e6-90ad-eb3ca423edff.png">

**Comment by ambidextrousTx** [comment]
Hi @luthraprerna  - this is a known issue with scalability in our system right now. We are working on a fix-pack that is going to resolve these kinds of connectivity issues going forward. Please watch out for our update.

**Comment by hansb001** [comment]
Hi @ambidextrousTx I have the same issue, on a Mac and a Windows machine.. The parent cannot connect. When will this fix-pack be available?

**Comment by ambidextrousTx** [comment]
@hansb001 we have a fix in for lazily restarting the parents in the server container that we're testing right now. We have another fix going in that will do some smart cleanup of parents not being used (which can be brought back alive on demand). That and some concurrency fixes are going in and will be tested thoroughly. We hope to release the fix-pack right after the Thanksgiving break. Thank you for your patience.

**Comment by gitwouter** [comment]
same issue here... looking forward to the fix

**Comment by hailunw** [comment]
Same issue

**Comment by juanitodur** [comment]
Hi, Exact same issue here! Hope the fix arrives soon! Thanks!

**Comment by sanjayko** [comment]
Yes, its right now going through test in staging, hoping to get green light for move tonight or tomorrow

Thanks

Sanjay

**Comment by sanjayko** [comment]
The fix is in, if you still have issues please create a new organization and continue.

**Comment by nd541** [comment]
I downloaded the installation version from Intu Gateway https://rg-gateway.mybluemix.net/Downloads,  but I still get the same issue. Does it still have the old version? Do you know when the new version with your fix will be updated?

**Comment by ambidextrousTx** [comment]
@nd541 Did you create a new organization after downloading, or are you using the organization you had created earlier?

**Comment by nd541** [comment]
Yes, I just created a new org and run install again, still get authorized error
![image](https://cloud.githubusercontent.com/assets/11544882/21276542/f4e14fac-c39f-11e6-9b44-ff8017a7d7a5.png)

**Comment by gitwouter** [comment]
I believe you can ignore the LanguageTranslationV1 connection error. The code is referring to the previous version of that service and its URL has changed on Bluemix. Everything works without that service though. Do the other services work?

**Comment by ambidextrousTx** [comment]
@nd541 I am seeing your parent instance up and running with two children authenticated on the server container:

`{
   "children" : [
      {
         "authenticated" : true,
         "selfId" : "a0acae964633be4372334f3033f9727c"
      },
      {
         "authenticated" : true,
         "selfId" : "6fecf0c26b7b3225b8e488db53411993"
      }
   ],
   "name" : "CASParent",
   "selfId" : "62dc76e455894811e44dff50f0c6e354",
   "topics" : [
      {
         "topicId" : "agent-society",
         "type" : "application/json"
      },
      {
         "topicId" : "audio-out",
         "type" : "audio/L16;rate=22050"
      },
      {
         "topicId" : "blackboard",
         "type" : "application/json"
      },
      {
         "topicId" : "blackboard-stream",
         "type" : "application/json"
      },
      {
         "topicId" : "body",
         "type" : "application/json"
      },
      {
         "topicId" : "gesture-manager",
         "type" : "application/json"
      },
      {
         "topicId" : "graph-skills",
         "type" : "application/json"
      },
      {
         "topicId" : "log",
         "type" : "application/json"
      },
      {
         "topicId" : "sensor-manager",
         "type" : "application/json"
      },
      {
         "topicId" : "topic-manager",
         "type" : "application/json"
      }
   ],
   "type" : "Linux"
}` - it might have been a temporary network issue? Did you get it work?

**Comment by nd541** [comment]
Yes thanks. I saw all the services green, just the language translation red.

**Comment by peterschleinitz** [comment]
My Intu manager is still connecting to parent: 
[12/21/16 22:06:12][ERRO][Request] Request Error 401: {
  "code": 401,
  "error": "Not Authorized",
  "description": "No credentials supplied."
}

**Comment by ambidextrousTx** [comment]
@peterschleinitz Are you seeing something like `[WebClient] WebSocket failed to connect` or just that 401 that you have posted?

**Comment by peterschleinitz** [comment]
exactly: [ERRO][WebClient] Websocket failed to connect, status code 401:  Not Authorized
