### ISSUE TITLE
Error failed synch

### ISSUE THREAD

**Issue by LucaDev13** [watson-intu/self-sdk#6]
This issue is happening on a 10.12.1 MacOS Sierra.  Before experiencing this, I have experienced the "Connecting to parent.." issue which is currently being fixed.

As far as I can tell this issue started occurring after organisation changes that I made within Intu Gateway, specifically deleting the original, default organisation and creating a new one. 

This issue occurs at point 4 of Installing Intu described in the [code section](https://github.com/watson-intu/self-sdk) of this repo.

![image](https://cloud.githubusercontent.com/assets/4184358/20410178/bcd3162e-ad13-11e6-84fc-4359d856fd9f.png)
![image](https://cloud.githubusercontent.com/assets/4184358/20410193/cac322ec-ad13-11e6-9628-83146537c8fa.png)
![image](https://cloud.githubusercontent.com/assets/4184358/20410197/d6341352-ad13-11e6-9528-03373d20c222.png)

**Comment by ereneld** [comment]
This is related possible timeout issue. It didn't show after re-try.

**Comment by LucaDev13** [comment]
This keeps happening both with Mac0S 10.12.3 and also with Windows 10 with exactly the same behaviour with Chrome or Firefox. I've raised with the bluemix team, at this point I am assuming it could be due to something wrong on bluemix side.

**Comment by LucaDev13** [comment]
I think this can be closed, I have opened a new Bluemix account and it worked without issue. This was due to some Bluemix bug within organisation from what I saw.
