### ISSUE TITLE
Using different conversation workspace

### ISSUE THREAD

**Issue by juanitodur** [watson-intu/self-sdk#9]
Hello!

After the fix you've released I've managed to make it work! Thanks for that. I've been trying to spice it up a little bit by using a workspace of my own, I can't seem to make it work. On the self-dialog parameter I enter  my workspace id but it is not being recognized. It keeps saying things like "I do not know how to agree" or "...greetings" etc. 

I wonder if the key Self-domain has anything to do with this issue. I could not find any parameter like that in my personal conversation service, or workspace. Furthermore, the endpoint, username and password are correct (write back the example workspace id and it works perfectly, also even if I change dialogs inside it, they are recognized)

Does anyone know how to use an existing workspace? I do not want to overwrite the example's dialogs, intents and entities...too much work...XD

Thank you!

**Comment by kbanks9** [comment]
Hey, in order for Conversation service responses to be triggered you need to add "dialog_" to all of your intents in your Conversation workspace (ex: "dialog_greetings" or "dialog_agree").  After Conversation service is done training, the "I don't know how to _____" responses should go away.

**Comment by juanitodur** [comment]
It worked! Thanks
